### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by flukeout** [ActiveState/p532#1]
* [ ] Mobile Styling
* [ ] Get proper CLI commands in there
* [ ] Figure out if we want to say Mac coming soon and where to send people on macs
* [ ] CTA to create account or at least link to platform?
* [ ] Link to blog about new Perl?
* [x] page `<title>`
